version: "3"
services:
  # api-gateway:
  #   build:
  #     context: ./gateway
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - customer
  #     - shopping
  #     - products

  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
    networks:
      - mern-network

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - mern-network

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
    env_file:
      - ./products/.env.dev
    networks:
      - mern-network
  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
    env_file:
      - ./shopping/.env.dev
    networks:
      - mern-network
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    env_file:
      - ./customer/.env.dev
    networks:
      - mern-network
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge